apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb2:8086
    basicAuth: true
    secureJsonData:
      token: <influx-api-token>
    jsonData:
      organization: ITM
      defaultBucket: SS-Anthem
      version: Flux
      tlsSkipVerify: false
      withCredentials: true
    uid: xU6Z19aVk

  - name: Infinity
    type: yesoreyeram-infinity-datasource
    access: proxy
    jsonData:

  - name: grafana-mqtt-datasource
    type: grafana-mqtt-datasource
    uid: PBA9FB8DAC51D59B8
    orgId: 1
    access: proxy
    isDefault: true
    readOnly: false
    editable: true
    jsonData: 
      uri: "ssl://broker:1883"
      tlsSkipVerify: true

  - name: Prometheus
    type: prometheus
    url: https://nginx-reverse-proxy/prometheus
    access: proxy
    isDefault: false
    jsonData:
      tlsSkipVerify: true  # This disables certificate verification
